# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Pod
metadata:
  name: linuxbox
spec:
  restartPolicy: OnFailure
  # nodeSelector:
    # eks.amazonaws.com/fargate-profile: emr
    # eks.amazonaws.com/nodegroup: i3en2
  containers:
  - name: linuxbox
    # image: amazonlinux:latest
    image: eclipse-temurin:8-jdk-focal
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
