image:
  repository: public.ecr.aws/myang-poc/celeborn-rss
  tag: spark3.3_8-jdk
  # tag: spark3.5_17-jdk
  pullPolicy: Always

nodeSelector:
  app: rss

# master replicas should not less than 3 for HA
masterReplicas: 3
workerReplicas: 3
hostNetwork: false
dnsPolicy: ClusterFirst

resources:
  # -- Pod resources for Celeborn master pods
  master: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- Pod resources for Celeborn worker pods
  worker: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

securityContext:
  runAsUser: 10006
  runAsGroup: 10006
  fsGroup: 10006
priorityClass:
  master:
    create: false
    name: ""
    value: 1000000000
  worker:
    create: false
    name: ""
    value: 999999000
volumes:
  master:
    - mountPath: /rss1/rss_ratis/
      hostPath: /local1/rss_ratis
      type: hostPath
      capacity: 100g
  worker:
    - mountPath: /rss1/disk1
      hostPath: /local1/disk1
      type: hostPath
      diskType: SSD
      capacity: 2t
    - mountPath: /rss2/disk2
      hostPath: /local2/disk2
      type: hostPath
      diskType: SSD
      capacity: 2t
# celeborn configurations      
celeborn:
  celeborn.master.ha.enabled: true
  celeborn.metrics.enabled: true
  celeborn.metrics.prometheus.path: /metrics/prometheus
  celeborn.master.metrics.prometheus.port: 9098
  celeborn.worker.metrics.prometheus.port: 9096
  celeborn.worker.monitor.disk.enabled: true
  celeborn.shuffle.chunk.size: 8m
  celeborn.rpc.io.serverThreads: 64
  celeborn.rpc.io.numConnectionsPerPeer: 8
  celeborn.replicate.io.numConnectionsPerPeer: 24
  celeborn.rpc.io.clientThreads: 64
  celeborn.rpc.dispatcher.numThreads: 4
  celeborn.worker.flusher.buffer.size: 256K
  # celeborn.worker.flusher.threads: 512
  # celeborn.worker.flusher.ssd.threads: 512
  celeborn.worker.fetch.io.threads: 256
  celeborn.worker.push.io.threads: 128
  celeborn.client.push.stageEnd.timeout: 120s
  celeborn.worker.commitFiles.threads: 128
environments:
  CELEBORN_MASTER_MEMORY: 4g
  CELEBORN_MASTER_JAVA_OPTS: "-XX:-PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:gc-master.out -Dio.netty.leakDetectionLevel=advanced"
  CELEBORN_WORKER_MEMORY: 4g
  CELEBORN_WORKER_OFFHEAP_MEMORY: 24g
  CELEBORN_WORKER_JAVA_OPTS: "-XX:-PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:gc-worker.out -Dio.netty.leakDetectionLevel=advanced"
  CELEBORN_NO_DAEMONIZE: 1
  TZ: "Australia/Melbourne"

podMonitor:
  enable: true
  podMetricsEndpoint:
    scheme: http
    interval: 5s
    portName: metrics

service:
    type: ClusterIP
    port: 9097
cluster:
  name: cluster

# configmap: celeborn-conf
affinity:
  master:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - celeborn
              - key: app.kubernetes.io/role
                operator: In
                values:
                  - master
          topologyKey: kubernetes.io/hostname
  worker:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - celeborn
              - key: app.kubernetes.io/role
                operator: In
                values:
                  - worker
          topologyKey: "kubernetes.io/hostname"

